name: Deploy to Host

on:
  push:
    branches:
      - next

permissions:
  contents: read
  packages: write

env:
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: root
  SSH_PASS: ${{ secrets.SSH_PASS }}
  PORT: 8080
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}
  APP_NAME: webmc

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Global Dependencies
        run: npm install --global vercel pnpm@9.0.4
      - name: Write Release Info
        run: |
          echo "{\"latestTag\": \"$(git rev-parse --short $GITHUB_SHA)\"}" > assets/release.json
      - name: Create config.local.json
        run: echo '${{ vars.CONFIG }}' > config.local.json
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASS }}
          script: |
            # Check if Docker is installed, and install it if not
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found, installing..."
              apt-get update
              apt-get install -y docker.io
              systemctl start docker
              systemctl enable docker
            else
              echo "Docker is already installed"
            fi

            echo "Logging into GitHub Container Registry..."
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

            echo "Pulling the new Docker images..."
            docker pull ${{ env.DOCKER_IMAGE }}:latest

            echo "Stopping and removing existing containers..."
            docker stop ${{ env.APP_NAME }} || true
            docker rm ${{ env.APP_NAME }} || true

            echo "Running the new container..."
            docker run -d \
              --name ${{ env.APP_NAME }} \
              -p 80:${{ env.PORT }} \
              -e PORT=${{ env.PORT }} \
              --restart always \
              ${{ env.DOCKER_IMAGE }}:latest

            # Keep only the last 3 versions of images
            echo "Cleaning up old images..."
            docker image ls ${{ env.DOCKER_IMAGE }} --format "{{.ID}}" | tail -n +4 | xargs -r docker image rm -f

            echo "Deployment completed successfully."
